MINI-TEAM3/client

src/components/Buttons/AnnualBtn.tsx
src/components/Buttons/Btn.tsx
src/components/Buttons/DutyBtn.tsx
src/components/Buttons/ModalBtn.tsx

<br />
- 페이지용 버튼 구현
- 휴가 신청/당직 수정 버튼 구현
- 버튼 hover 시에 opacity 변화 추가
<br />
- `ModalBtn` 컴포넌트 내 hover 효과가 추가되었습니다.

:sparkles: Feat: 페이지용, 휴가 신청, 당직 수정 버튼 구현 및 hover 효과 추가

---

src/styles/GlobalStyle.ts

<br />
`src/styles/GlobalStyle.ts` 파일 내 전역 스타일 값을 수정했습니다.
<br />
- :root 아래 body 추가 및 `{ margin: 0; }` 수정
- `<body>` background-color 추가
- `<button>` font-family 추가

:lipstick: Design: 전역 스타일 추가

---

src/App.tsx
src/MockData/User.ts
src/components/SideBar.tsx
src/styles/Themes.ts

<br />
사이드바 프로그레스 테마 컬러 추가 : middleGray 
사이드바 레이아웃 구성 
사이드바 임시 목 데이터 연결 
<br />
사이드바 프로그레스 테마 컬러 추가 : middleGray 
목 데이터 폴더 추가, user데이터 임시 삽입 => 이후에 json 형식으로 변경 예정 
<br />

:sparkles: Feat: 사이드바 레이아웃구성, MockData 임시 연결

---

src/App.tsx
src/components/MainHeader.tsx
src/components/SideBar.tsx
src/pages/Layout.tsx
src/pages/index.tsx
src/styles/GlobalStyle.ts

<br />
- 라우터 수정 (SideBar-Main / Login, Sign-up 분리)
- 전역 스타일 수정

:sparkles: Feat: 라우터 수정, 글로벌 스타일 수정

---

src/components/Buttons/ApplyBtn.tsx
src/components/Buttons/ExelBtn.tsx
src/components/Buttons/RejectBtn.tsx

<br />
엑셀 다운로드 버튼 및 어드민 페이지에서 사용하는 승인/반려 버튼 UI 구현 완료했습니다.
<br />
추후 각 버튼마다 handler 연결 작업 필요합니다.

✨ Feat: 엑셀 다운로드 버튼, 어드민 승인/반려 버튼 UI 구현

---

src/components/SideBar.tsx
src/pages/MyPage.tsx
src/pages/Password.tsx
src/pages/UserInfo.tsx
src/pages/index.tsx
src/styles/Themes.ts

<br />
사이드바 마이페이지 하위 메뉴 추가 
Password 페이지 추가
<br />
MyPage -> UserInfo 페이지로 변경 
<br />

:sparkles: Feat: 사이드바 마이페이지 하위 메뉴 추가

---

index.html
package-lock.json
package.json
src/components/Buttons/Btn.tsx
src/lib/Validation/index.ts
src/pages/MyPage.tsx
src/pages/SignUp.tsx

<br />
회원가입 페이지(/signup)의 UI 구현을 완료합니다.
<br />
- react-hook-form 라이브러리 설치 (package.json)
- google font 'ABeeZee' 링크 추가 (index.html)
<br />
지난 merge 사항을 git pull , git rebase 시 본인 브랜치에서 코드 충돌 발생 (MyPage.tsx)
해결했으나 전체 코드상 오류가 있는지 확인 할 필요가 있습니다.

✨ Feat: 회원가입 페이지 UI 구현

---

src/components/SideBar.tsx

<br />
추가한 사이드바 서브메뉴 메뉴 클릭시 동작 수정 
(기존의 계속 보이기 -> 다른메뉴 클릭시 보이지 않았다가 마이페이지 클릭시 보이게) 
props warning 출력되지 않게 수정, 원인 해결 
<br />
font-size를 제외한 모든 속성 rem->px 수정 
<br />

:bug: Fix: 사이드바 서브메뉴 동작 수정, props warning 수정

---

src/components/MainHeader.tsx

<br />
메인 헤더 내 병원명을 User의 병원 코드로 변경합니다.
<br />
`<span>병원명</span>` -> `<span>{hospitalName}</span>`
<br />
추후 API 주소로 URL 변경 필요

✨ Feat: 메인 헤더 내 User 재직 병원 출력

---

src/lib/Validation/index.ts
src/pages/SignUp.tsx

<br />
회원가입 페이지 유효성 검사 추가 구현
<br />
추후 추가 예정
<br />

:sparkles: Feat: 회원가입 페이지 유효성 검사 추가

---

src/pages/SignUp.tsx
src/styles/GlobalStyle.ts

<br />
회원가입 기능 구현을 완료합니다.
<br />
기존 더미 데이터를 활용한 데이터 출력에서 배포 완료된 API로 연결
- 병원 데이터 출력 `/hospital/list`
- 과 데이터 출력 `/dept/{hospitalId}.list`
- 회원가입 핸들러 완성 (에러 핸들링 진행 중 - 추후 수정)
<br />
회원가입을 위한 요청 데이터 전송을 위해서 `hospitalName`,`deptName`을 `hospitalId`, `deptId`로 변환하는 과정에서
`index`를 사용하고 있지만 추후 더 나은 방법을 찾아 수정하겠습니다.

✨  Feat: 회원가입 API 연결, 기능 구현 완료

---

public/junehee/editPassword.json
src/pages/MyPage.tsx
src/pages/Password.tsx
src/pages/UserInfo.tsx

<br />
마이페이지 비밀번호 재확인, 개인정보 수정, 비밀번호 수정 UI 일부 수정
axios를 통한 API 호출 코드 초안 구현을 완료합니다.

📚 Docs: 마이페이지 비밀번호 재확인 UI 추가, 일부 코드 수정

---

src/lib/api/index.ts
src/lib/types/index.ts

<br />
API 호출 코드를 모듈화합니다.
<br />
`/types/client.ts`, `/types/miniAPI.ts` 파일 삭제
`/types/index.ts` 파일 생성

✨  Feat: API 모듈화

---

src/components/Modals/CalAnnualModal.tsx
src/components/Modals/CalDutyModal.tsx
src/components/Modals/Modal.tsx
src/components/Modals/RequestModal.tsx

<br />
금일 당직 조회, 금일 휴가 인원 조회 모달 디자인을 수정합니다.
<br />
<br />

:lipstick: Design: 모달 디자인 수정

---

src/components/SideBar.tsx

<br />
api 컬럼명 변경된 후 수정된 선언된 인터페이스 userdata타입 속성에 맞게 사이드바 수정 
<br />
사이드바 프로그레스 정렬 틀어진것 사소하게 수정! 
로그인한 사용자 과 출력 변수 변경된 이름으로 수정  
<br />

:bug: Fix: 사이드바 변경된 타입 속성에 맞게 수정

---

src/pages/SignUp.tsx

<br />
회원가입 API를 모듈 시스템으로 가져옵니다.
미사용 코드 및 `console.log()` 삭제합니다.
<br />
axios.create() 로 생성한 authInstance Header 내 token 오류

🔨 Refactor: 회원가입 API 모듈 연결, 미사용 코드 삭제

---

src/components/MainHeader.tsx

<br />
UserData 변경된 필드값(KEY) 재적용
<br />
`hospital_id` -> `hospitalId`

:bug: Fix: UserData 변경된 필드값 적용

---

src/components/Modals/CalAnnualModal.tsx
src/components/Modals/CalDutyModal.tsx
src/components/Modals/Modal.tsx
src/components/Modals/RequestModal.tsx
src/components/Modals/checkModal.tsx
src/lib/api/index.ts

<br />
휴가 신청, 당직 수정 요청 모달과 api를 연결합니다.
<br />
1. `requestModal.tsx`
리퀘스트 모달의 api를 모두 연결합니다. 에러가 있다면 메세지를 출력합니다.
2. `index.ts`
api 내의 index.ts의 당직 내용 수정 api에 헤더를 추가하고, error를 throw해 api 호출 내부에서 error를 확인 할 수 있도록 합니다.
> 충돌이 있을 수 있으니 확인해주세요!
3. `Modals`
전체적인 모달들의 사소한 스타일 수정이 있습니다.
4. `checkModal`
휴가, 당직 신청이 완료 되었다면 해당 요청이 끝났다는 것을 확인시켜주기 위한 모달을 생성하여 연결합니다.
<br />

✨ Feat: 리퀘스트 모달 api 연결

---

package-lock.json
package.json
src/components/Buttons/ExelBtn.tsx
src/components/Calendar/CalendarList.tsx
src/lib/api/index.ts
src/utils/decode.ts

<br />
캘린더 리스트 엑셀 다운로드 기능 추가
<br />
**엑셀다운로드 라이브러리 추가 설치**
캘린더 리스트 출력 형식 변경 
엑셀 다운로드 기능 추가 (엑셀 다운로드 버튼 컴포넌트)
휴가/당직 타입 한글로 변환 코드 추가 (utils/decode)
<br />

:sparkles: Feat: 캘린더 리스트 엑셀 다운로드 기능 추가

---

src/components/Modals/checkModal.tsx
src/lib/api/index.ts
src/pages/RequestList.tsx

<br />
자잘한 오류들을 수정합니다.
<br />
변경사항이 있다면 작성해주세요.
<br />

🐛 Fix: 소트 수정, 모달 error 핸들링 수정

---

src/components/Calendar/CalendarBody.tsx
src/components/Modals/CalDutyModal.tsx
src/lib/Validation/index.ts
src/lib/types/index.ts
src/pages/SignUp.tsx
src/pages/UserInfo.tsx

<br />
마이 페이지 프로필 이미지 수정 기능 추가

🔨  Refactor: 마이페이지 프로필 이미지 수정 기능 추가, 미사용 코드 삭제

---

.gitignore
src/components/DashBoard.tsx
src/lib/api/index.ts
src/pages/Password.tsx
src/pages/SignUp.tsx
src/pages/UserInfo.tsx

<br />
- API Base URL 환경변수 처리
- async-await try ~ catch 수정
<br />
.env 파일 만드셔서 아래 변수로 API URL 할당 해주시면 됩니다!
```
VITE_BASE_URL =  ''
```
<br />
지난 번 승이님이 리뷰해주신 대시보드는 API 완성되면 데이터 할당 해보고 더 편한 방법으로 리팩토링 하려고 아직 map 미적용 상태입니닷 ~

🔨  Refactor: API Base Url 및 async-await try ~ catch 관련 로직 수정

---

src/components/DashBoard.tsx
src/lib/api/index.ts
src/lib/types/index.ts
src/pages/Attendance.tsx
src/utils/convertDay.ts
src/utils/convertTime.ts

<br />
API 응답값으로 데이터 연결하면서 대시보드 컴포넌트 코드가 일부 수정되었습니다!
다슬님께서 아마 이전 컴포넌트 형태로 관리자 페이지에 가져가셨을건데 PR 올려주시면 제가 나중에 수정하겠습니다!
<br />
- API/index.ts 병원 부서 호출 엔드 포인트 변경되었습니다.
- 대시보드 컴포넌트가 일부 변경되었습니다.
<br />
closed #78

✨  Feat: 대시보드 근무 관리 데이터 연결

---

package.json

<br />
package.json scipt 중 build 내용을 수정
<br />
- 기존 tsc && vite build
- 수정 npm install & tsc && vite build

⚙️ Chore: build 스크립트에 npm i 추가

---

package-lock.json
src/components/Alert.tsx

<br />
Netlify 배포 중 발생한 오류 수정
<br />
- npm audit fix 를 통한 오류 해결
- react-icons import 구문 수정 (react-icons/Io5 -> react-icons/io5)
<br />

🐛 Fix: 빌드 오류 수정

---

src/lib/api/index.ts

<br />
PR 내용을 간단히 요약해서 작성하세요.
<br />
변경사항이 있다면 작성해주세요.
<br />

🌷 Release: v2.0.0 배포
